### PR TITLE
Just some random refactoring

### PR DESCRIPTION
**Pull request by GabrielRavier**
Most notably removed nullptr checks before delete and free (redundant)
Corrected the disassembling of sub which returned add
Corrected a buncha printf arguments

Signed-off-by: Gabriel Ravier <gabravier@gmail.com>

### CODE REVIEW

**Comment by hch12907** [comment]
I thought `delete`-ing nullptr is a no-op?

**Comment by GabrielRavier** [comment]
As far as i know, deleting nullptr **is a nop**, but you can put the checks back in anyway since you can modify my branch
image

Btw, I'd put the blame on the standard library if that's the reason it crashed. Otherwise, could you please clarify what the actual cause of the crash is ?

**Comment by PSI-Rockin** [comment]
It works fine on my compiler (clang), but @refractionpcsx2 reported crashing when loading a ROM. He uses Visual Studio. Perhaps it's an issue with his setup, or just Visual Studio being silly as always. Regardless, if it is a standard library issue, that means that removing the checks is non-portable and should not be done.

**Comment by GabrielRavier** [comment]
I don't really have my compiler on hand, so I can't just un-remove the checks.

I've already said twice that contributors can modify my branch though

**Comment by tokumeiwokiboushimasu** [comment]
And, you can modify, too ;-)
If you want some PR to be merged, it is typical that you have to modify it following reviews.

**Comment by PSI-Rockin** [comment]
After some further investigation, it looks like it's not crashing anymore? Dunno what was going on, probably some cosmic ray condition. Either way, I assume then removing the nullptr checks won't hurt anything.

I'll review the rest of this PR sometime. One thing to consider: I'm not going to modify your PR, because it's not my code. None of the other contributors are going to modify your PR either. If there's a genuine problem that we point out (unlike the nullptr thing), then it's your responsibility to fix it.

**Comment by GabrielRavier** [comment]
I mean tbh I was just thinking that there was a point to that feature but I mean yeah there might just not be one.

**Comment by GabrielRavier** [comment]
I'll just close this and put some of these as issues if they haven't been fixed since now I guess

**Pull request closed without merging**
