### PR TITLE
Use spdlog for console logging

### PR DESCRIPTION
**Pull request by arcum42**
This is a work in progress.

spdlog is a header-only library for handling logging to console and files, allowing for similar logging functionality to pcsx2.

**To do:**
Add in any loggers I have missed.
Convert over all the printf statements to spdlog. (I've converted a few files, but not most.)
Assign colors to the different loggers.
~~Allow for turning on and off individual loggers.~~
~~Add options in the gui for logging. (Probably waiting for the UI Updates PR to be merged first)~~
Customize what file the log gets written to, and allow you to turn on and off ~~console and~~ log writing.
~~Get it working in build systems other than cmake.~~

I'm open to feedback and ideas, and I could use to know what to change (and whether this is even a good idea) before I implement things across the board.

(For example, instead of having externs for a dozen logger variables, we could use spdlog::get(<log name>) across the board, and I'm not sure which I prefer.)

Note that this does use the fmt library for the logs. For example:
gs_logger->debug("Buffer width: {}", tex0.width);
gs_logger->debug("TEX0: {:#08x}_{:#08x}", value >> 32, value & 0xFFFFFFFF);

For reference:
https://github.com/gabime/spdlog
https://github.com/fmtlib/fmt

### CODE REVIEW

**Comment by arcum42** [comment]
Ah, the fun of rebasing. Hopefully I didn't accidentally revert anything.

I'm holding off on colors for a while, because while colors are easy if you only have a color sink, it seems to be more difficult when you have both a color sink and a sink for logging files for some reason. I'll figure out what I'm missing later.

Interesting when I randomly pick a ps2 game to test with (Orphen) and find out it's broken in Dobiestation...

**Comment by arcum42** [comment]
I've been able to compile this in both qmake and Visual Studio now, regardless of AppVeyor. I think the submodule may be giving it grief.

I caught a mistake in the vcxprog file regarding debug builds of libdeflate while I was at it...

**Comment by tadanokojin** [comment]
You likely need to modify the appveyor build to perform a recursive clone or a submodule init after the clone (modify appveyor.yml). The examples I see online seem to do it by:
```yml
install:
- git submodule update --init --recursive
```
Generally, this is why I personally prefer to avoid git submodules.
Anyway, thank you for fixing the build.

**Comment by arcum42** [comment]
> You likely need to modify the appveyor build to perform a recursive clone or a submodule init after the clone (modify appveyor.yml). The examples I see online seem to do it by:
> 
> ```yaml
> install:
> - git submodule update --init --recursive
> ```
> 
> Generally, this is why I personally prefer to avoid git submodules.
> Anyway, thank you for fixing the build.

No problem. And that does look about like the command I've been running after switching to that branch to get the submodule to pull in. I suppose I could've just copied the library in, but a submodule seemed like it should've been the right way to do it.

And no problem. When I went to try compiling it, I immediately tried a debug build without a release one first and ran into the problem with libdeflate...

**Comment by arcum42** [comment]
Besides adding the git submodule command, I also had to add the path and name of the project file. Looks like appveyor likes it now!

**Comment by tadanokojin** [comment]
praise dobie!

**Comment by arcum42** [comment]
I discovered there is a way to turn off automatic endlines in the logger, and added back in all the \n's. There are enough spots that the formatting was being messed up that I'll go this way, and we can change it later if we get a good workaround for those spots. 

For my own reference:
ds_log([^"]+)"(.*)"
ds_log$1"$2\\n"

**Comment by tadanokojin** [comment]
Heads up: #193 removes the `build` section in favor of just passing the command to build for Windows. I don't think it should be required once that is merged.

Also, not being familiar with this library. I'm curious on your thoughts concerning adding a console window to the UI. We might just be able to capture the output stream but I'm curious is spdlog provides and facilities we can use.

**Comment by arcum42** [comment]
> Heads up: #193 removes the `build` section in favor of just passing the command to build for Windows. I don't think it should be required once that is merged.
> 
> Also, not being familiar with this library. I'm curious on your thoughts concerning adding a console window to the UI. We might just be able to capture the output stream but I'm curious is spdlog provides and facilities we can use.

I don't think that'll cause problems with the two changes I made. Hopefully not.

The way spdlog works is that you set up one or more loggers (the way I currently have it set up, there's one for every component: ee, iop, etc...), and you assign the loggers what's termed a 'sink', which determines where it outputs to. One of the sinks is a multisink, so I set up one of those and told it to have in it one sink for console output and another for writing to a file.

In fact, I set that all up on one logger, then cloned it a bunch of times.

What you'd actually want to do in this case is set up a custom sink that outputs to the console window, and add that into the multisink as well. There is a section on the wiki describing how to create a custom sink, though I haven't really looked into it much...
https://github.com/gabime/spdlog/wiki/4.-Sinks

**Comment by tadanokojin** [comment]
Well the `project` specifier you added will likely cause a git conflict which is why I mentioned it.
https://github.com/PSI-Rockin/DobieStation/blob/d14d412f85175c394d4248caff2dc378840e792c/appveyor.yml#L17-L19

The submodule command I think should be good. I think not specifying `sh` or `cmd` means it runs on both Win and Linux builds.

Thanks for the info. I'll take a look at it when I get a moment. Probably outside the scope of this PR.

**Comment by arcum42** [comment]
> Well the `project` specifier you added will likely cause a git conflict which is why I mentioned it.
> [DobieStation/appveyor.yml](https://github.com/PSI-Rockin/DobieStation/blob/d14d412f85175c394d4248caff2dc378840e792c/appveyor.yml#L17-L19)
> 
> Lines 17 to 19 in [d14d412](/PSI-Rockin/DobieStation/commit/d14d412f85175c394d4248caff2dc378840e792c)
> 
>  build: 
>    verbosity: normal 
>    project: Dobiestation\DobieStation.sln 
> The submodule command I think should be good. I think not specifying `sh` or `cmd` means it runs on both Win and Linux builds.
> 
> Thanks for the info. I'll take a look at it when I get a moment. Probably outside the scope of this PR.

Ah, right, that was in build. Hmm. Hope not then. As long as you are pointing to which project to use someplace, anyways. The reason I needed to add in the project section is that it was getting confused. I think there's a sln file somewhere in spdlog.

No problem. And yeah, I'm mostly concentrating on getting everything converted over at the moment. In fact, the multisink thing is why I haven't done colors yet. If your logger has a color sink, you can change the color, but you can't on other sinks, and the color sink is in the multisink. I'm sure there's a way around it, but I decided I'd worry about it later.

I also need to actually get it to save and load the settings from my menus, since right now it just goes with the same defaults every time you start it up. Got that halfway working locally, but there's an odd bug someplace...

**Comment by tadanokojin** [comment]
> The reason I needed to add in the project section is that it was getting confused. I think there's a sln file somewhere in spdlog.

Yeah I ran into some issues as well so instead I decided to pass the command instead of relying on appveyor to make it for me. So it shouldn't cause issues with the build anymore since I'm explicitly passing the SLN now.

https://github.com/PSI-Rockin/DobieStation/blob/63a4d9ce395b3ebf4bd1010d799d046eb6de32db/appveyor.yml#L46-L51

**Comment by PSI-Rockin** [comment]
This PR has been up for quite a long time, and it doesn't seem any progress will be made. I'll go ahead and close this unless there's any objections.

**Pull request closed without merging**
