### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by Margen67**
[Example Run](https://github.com/Margen67/DobieStation/actions/runs/35233920)
This doesn't have artifacts for cmake since I don't know where they end up.

What this builds:
 * Windows (Visual Studio 2019):
    * MSVC (Release Optimized, Release, Debug, Devel)
  * Linux (Ubuntu 18.04): 
     * cmake (Release, RelWithDebInfo, Debug)
     * qmake
  * macOS (10.15):
     * cmake (Release, RelWithDebInfo, Debug)
     * qmake

AppVeyor differences:
  * Pros:
      * Faster than AppVeyor (can build multiple jobs/configurations at the same time)
  * Cons:
      * Can't link to latest artifacts
      * Can't delete builds
      * Doesn't have Qt preinstalled

### CODE REVIEW

**Comment by InfamousKnight** [comment]
In the example run, is that for latest commit or the latest commit when you made this pr? It would be nice to have as this is pretty hard to compile on windows.

**Comment by Margen67** [comment]
@InfamousKnight It's based on https://github.com/PSI-Rockin/DobieStation/commit/8a181b648e3105896d4ca09d1a10c5dc5f48c3de.
There's already CI (AppVeyor) but it's slow.

**Comment by InfamousKnight** [comment]
Hmm, wheres the link for appveyor build?

**Comment by Margen67** [comment]
https://ci.appveyor.com/project/PSI-Rockin/dobiestation/history

**Pull request merged**
