### PR TITLE
Move CONTRIBUTING.md to .github, add FUNDING.yml

### PR DESCRIPTION
**Pull request by Margen67**
CONTRIBUTING.md is moved to .github so it doesn't trigger builds for #275.

https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

### CODE REVIEW

**Comment by tadanokojin** [comment]
CONTRIBUTING.md is also in the vs project

**Comment by Margen67** [comment]
@tadanokojin I fixed that, and a README url I missed.

Would `$(RootDir).github\*` work?

**Comment by tadanokojin** [comment]
Docs seem to suggest so and indeed I tried it and it does seem to work.
I'm not opposed to it's usage for that folder if it makes things easier for you.

**Comment by Margen67** [comment]
This should be ready to merge now.

**Comment by tadanokojin** [comment]
Sounds good.

**Comment by Margen67** [comment]
This needs to be enabled for the Sponsor button to show up https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

**Comment by PSI-Rockin** [comment]
Okay, I've enabled the button. Thanks for your work.

**Pull request merged**
