### PR TITLE
Load ELF in Menu Bar

### PR DESCRIPTION
**Pull request by DidgeridooMH**
Added a menu bar to the main window.
Outsourced loading roms to it's own function.
Created three items in the menu bar to load the elf with or without bios skip and to exit the program.
This allows the program to start only with a bios path provided and the ROM can be loaded after.

### CODE REVIEW

**Comment by PSI-Rockin** [comment]
Good to see another contributor :)

First things first, remove the tabbing/eight spaces from the changes and make it four spaces, to maintain continuity with the codebase. I think that's something GitHub does, which is a bit annoying; there should be a setting somewhere to adjust tab width though.

**Comment by DidgeridooMH** [comment]
Sorry about that. I'm a bit new to working with group projects on github. I fixed the tab problem in my editor so it won't be a problem anymore.

**Comment by PSI-Rockin** [comment]
It's fine, more of a problem with GitHub than anything else.

I won't be able to review the code style until tomorrow, but I tested your PR. Here's a few things I'd like to say:

* The functionality of "Open Rom" and "Open Rom (Skip BIOS)" is flipped. Looks like you flipped the boolean values in the functions you've added.
* The emulator needs to be reset each time a ROM is successfully loaded. On that token, I would delete that `e.reset()` line in `EmuWindow::init` once you've done that.
* On macOS (which I use to develop), programs have a menubar attached to the top of the monitor rather than on the application. When booting from the terminal, the menubar is focused on Terminal, not DobieStation. It's not a huge concern, but I'd like for you to find a way to fix that.

**Comment by DidgeridooMH** [comment]
Okay I will probably be able to fix those issues later tonight. Although, I'm not quite certain what you mean by it not being focused on macos. Could you elaborate?

**Comment by DidgeridooMH** [comment]
I think I may have fixed the issue with the window not focusing but, I am on a windows system right now and have no way of testing it.

**Comment by PSI-Rockin** [comment]
Think I figured out what the issue was. DobieStation needs to be bundled as an App; otherwise, the focus remains on the Terminal and not DobieStation.

If that doesn't make much sense to you, don't worry about it for now. You can remove the changes you've made to try to get that "working", as it doesn't do anything.

I tested the newest commit as well. It seems to work fine; it still boots Mortal Kombat and other demos. I'll review the code in a couple of hours.

**Comment by DidgeridooMH** [comment]
I removed the window code.

**Comment by DidgeridooMH** [comment]
Okay I implemented the changes you requested.

**Comment by PSI-Rockin** [comment]
Seems good to me. Only suggestion though is to replace the "Load Rom" and "Load BIOS" names with "Load ROM... (Fast)" and "Load ROM (Boot BIOS)". Do that, and it should be good to go.

**Comment by DidgeridooMH** [comment]
I changed them to the names you suggested. Next time, I'll be sure to look through the code-style more carefully to make it a little easier on you.

**Comment by PSI-Rockin** [comment]
Sorry, I haven't been able to look at this for the past couple of days. I'll test and (hopefully) merge tomorrow.

**Comment by PSI-Rockin** [comment]
Good work. If you're interested, there's more Qt-related tasks you can work on. :)

**Pull request merged**
