### PR TITLE
UI Updates

### PR DESCRIPTION
**Pull request by tadanokojin**
This is a WIP

**TODO:**
- ~Allow opening main window without bios~
- ~Settings window~
- ~Bios file select in settings window~
- ~Extract bios version info for display~
- ~Recent items~
- ~Game list~
- ~Remember last rom dir~
- ~VU1 jit/interpreter selection~

If there is anything else anyone wants to see please leave a comment.

### CODE REVIEW

**Comment by MrCK1** [comment]
A nice feature to have would be an ini entry to save the previous ROM folder as opposed to resetting it on startup. Thanks.

**Comment by arcum42** [comment]
Sounds a bit like the rewrite I never got around to on the gui code I'd started. I still have code around for rearranging the menu items I could probably separate and apply to this.

Adding remembering the iso folder was on my mind as something to add as well. In fact, having a list of recent iso's you could choose from would be good as well...

**Comment by PSI-Rockin** [comment]
Since the VU recompiler stuff has been merged, could you add something in the settings panel to switch between VU interpreter and recompiler?

**Comment by tadanokojin** [comment]
That should be everything now.

**Pull request merged**
